name: j-pet-continuous-integration-tests
on: [push, pull_request]

jobs:
  build_and_run_all_tests_on_ubuntu:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
   
    steps:
    - uses: actions/checkout@v2
    - name: system update
      run: |
       sudo apt-get -qq update
       sudo apt-get install -y git libboost-all-dev libtbb-dev cmake
      
    - name: download  ROOT 
      run: |
        wget https://root.cern.ch/download/root_v6.14.00.Linux-ubuntu18-x86_64-gcc7.3.tar.gz
        tar xzf root_v6.13.08.Linux-ubuntu18-x86_64-gcc7.3.tar.gz
    - name: cmake
      run: |
        source root/bin/thisroot.sh
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        source root/bin/thisroot.sh
        cd build
        make all tests -j4
    - name: run tests
      run: |
        source root/bin/thisroot.sh
        cd build
        source bin/thisframework.sh
        ls -l src/Unpacker2-download/Unpacker2-prefix/src/Unpacker2-build/
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:src/Unpacker2-download/Unpacker2-prefix/src/Unpacker2-build/
        ctest -j6 -C Debug -T test --output-on-failure
